#!/bin/sh

#INSTALL='collider.jam'
INSTALL='https://github.com/invider/collider.jam#develop'
PACKAGE=collider.jam

echo "Looking for $PACKAGE in global modules..."
MODULE=`npm list -g | grep $PACKAGE`

if [[ $MODULE == *$PACKAGE* ]]; then
    echo 'Found '$MODULE
    echo 'Uninstalling...'
    npm uninstall -g collider.jam

else
    echo 'Not found'
fi

echo "Installing package globally: $INSTALL"
npm install -g $INSTALL

echo "Testing installed version: "`jam version`

echo "Ready!"
echo "Running test server"
jam -t -d play

